2021-10-03 16:13:38 jdbc[7]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:242)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:182)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:228)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 8 more
2021-10-03 21:51:23 jdbc[15]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "id" not found; SQL statement:
 INSERT INTO "driver_entity" ("id", "description", "stars", "user_id") VALUES (2991282647, E'Dream meet strong contain fill tree. Husband investment our more.', 3, 26171131270)  [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:708)
	at org.h2.command.Parser.parseColumn(Parser.java:1377)
	at org.h2.command.Parser.parseColumnList(Parser.java:1362)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1731)
	at org.h2.command.Parser.parseInsert(Parser.java:1684)
	at org.h2.command.Parser.parsePrepared(Parser.java:891)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-10-03 21:51:23 jdbc[16]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "driver_entity_user_id" not found; SQL statement:
 INSERT INTO "driver_entity" ("driver_entity_user_id", "ratings_id") VALUES (2991282647, 26171131270)  [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:708)
	at org.h2.command.Parser.parseColumn(Parser.java:1377)
	at org.h2.command.Parser.parseColumnList(Parser.java:1362)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1731)
	at org.h2.command.Parser.parseInsert(Parser.java:1684)
	at org.h2.command.Parser.parsePrepared(Parser.java:891)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-10-06 12:57:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
SELECT * FROM "user_entity" where id = 36653272920 [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:205)
	at org.h2.command.dml.Select.prepare(Select.java:1248)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-06 12:58:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
SELECT id FROM "user_entity" [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Select.prepare(Select.java:1245)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-06 12:58:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
SELECT ID FROM "user_entity" [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Select.prepare(Select.java:1245)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-06 12:58:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
SELECT ID FROM "user_entity" [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Select.prepare(Select.java:1245)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-06 13:00:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "36653272920" not found; SQL statement:
SELECT * FROM "user_entity" where "id" = "36653272920" [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:207)
	at org.h2.command.dml.Select.prepare(Select.java:1248)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-06 22:43:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "restaurant_entity_menu""restaurant_entity_promotions" not found; SQL statement:
SELECT * FROM "restaurant_entity_menu""restaurant_entity_promotions" [42102-199]
2021-10-06 23:28:04 jdbc[8]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT DISTINCT * FROM ""restaurant_entity_menu""
INSERT INTO[*] ""restaurant_entity_menu"" (""restaurant_entity_id"", ""menu_id"")"; SQL statement:
SELECT DISTINCT * FROM "restaurant_entity_menu"
INSERT INTO "restaurant_entity_menu" ("restaurant_entity_id", "menu_id") [42000-199]
2021-10-06 23:54:12 jdbc[8]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table  not found; SQL statement:
SELECT * FROM ""promotions_entity"" [42102-199]
2021-10-06 23:59:54 jdbc[61]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (restaurant_entity_ratings: ""ratings_id"" BIGINT NOT NULL)"; SQL statement:
INSERT INTO "restaurant_entity_ratings" ("restaurant_entity_id", "ratings_id") VALUES (72004464641, E'') -- (72004464641, '') [22018-199]
2021-10-07 00:22:39 jdbc[8]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "TRUNCATE TABLE ""restaurant_rating_entity"" CASCADE[*]"; SQL statement:
TRUNCATE TABLE "restaurant_rating_entity" CASCADE [42000-199]
2021-10-07 00:22:45 jdbc[8]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Cannot truncate "PUBLIC.restaurant_rating_entity"; SQL statement:
TRUNCATE TABLE "restaurant_rating_entity" [90106-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.ddl.TruncateTable.update(TruncateTable.java:43)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-09 17:45:45 jdbc[38]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "TIMESTAMP" constant "N/A"; SQL statement:
INSERT INTO "order_entity" ("id", "active", "address", "delivery", "driver_note", "delivery_slot", "driver_accept", "order_complete", "placed", "restaurant_accept", "restaurant_complete", "restaurant_start", "delivery_price", "food_price", "tip", "refunded", "restaurant_note", "driver_user_id", "user_id", "confirmation_code", "payment_confirmed") VALUES (50808404584, false, E'5369 Aaron Walks
Nampa, US', false, E'N/A', E'N/A', false, false, true, false, false, false, 0, 46.78, 0, false, E'Result west though window lay support purpose where. Training buy season law hand brother pretty. Cause choice himself stock manager. Draw run decision since go card end.', E'N/A', 1780494965, E'87848141', false) -- (50808404584, FALSE, STRINGDECODE('5369 Aaron Walks\nNampa, US'), FALSE, 'N/A', 'N/A', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 0, 46.78, 0, FALSE, 'Result west though window lay support purpose where. Training buy season law hand brother pretty. Cause choice himself stock manager. Draw run decision since go card end.', 'N/A', 1780494965, '87848141', FALSE) [22007-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:140)
	at org.h2.value.Value.convertToTimestamp(Value.java:1099)
	at org.h2.value.Value.convertTo(Value.java:778)
	at org.h2.value.Value.convertTo(Value.java:735)
	at org.h2.table.Column.convert(Column.java:199)
	at org.h2.command.dml.Insert.insertRows(Insert.java:164)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: N/A
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:366)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:528)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:138)
	... 13 more
2021-10-09 17:46:19 jdbc[41]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "TIMESTAMP" constant "N/A"; SQL statement:
INSERT INTO "order_entity" ("id", "active", "address", "delivery", "driver_note", "delivery_slot", "driver_accept", "order_complete", "placed", "restaurant_accept", "restaurant_complete", "restaurant_start", "delivery_price", "food_price", "tip", "refunded", "restaurant_note", "driver_user_id", "user_id", "confirmation_code", "payment_confirmed") VALUES (1431041056, false, E'6338 Curtis Manors
Gainesville, US', false, E'N/A', E'N/A', false, false, true, false, false, false, 0, 34.59, 0, false, E'Property son hospital lead player hour agree. The street pick opportunity.', E'N/A', 78335801254, E'55230615', true) -- (1431041056, FALSE, STRINGDECODE('6338 Curtis Manors\nGainesville, US'), FALSE, 'N/A', 'N/A', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 0, 34.59, 0, FALSE, 'Property son hospital lead player hour agree. The street pick opportunity.', 'N/A', 78335801254, '55230615', TRUE) [22007-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:140)
	at org.h2.value.Value.convertToTimestamp(Value.java:1099)
	at org.h2.value.Value.convertTo(Value.java:778)
	at org.h2.value.Value.convertTo(Value.java:735)
	at org.h2.table.Column.convert(Column.java:199)
	at org.h2.command.dml.Insert.insertRows(Insert.java:164)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: N/A
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:366)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:528)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:138)
	... 13 more
2021-10-09 17:46:25 jdbc[44]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "TIMESTAMP" constant "N/A"; SQL statement:
INSERT INTO "order_entity" ("id", "active", "address", "delivery", "driver_note", "delivery_slot", "driver_accept", "order_complete", "placed", "restaurant_accept", "restaurant_complete", "restaurant_start", "delivery_price", "food_price", "tip", "refunded", "restaurant_note", "driver_user_id", "user_id", "confirmation_code", "payment_confirmed") VALUES (9515226675, true, E'20802 Mcdowell View
San Juan, US', false, E'N/A', E'N/A', false, false, true, false, false, false, 0, 100.31, 0, false, E'Change agent everyone front fall. Them total west. Character yeah wear political yard. I mention property relationship.', E'N/A', 34697077554, E'72468200', false) -- (9515226675, TRUE, STRINGDECODE('20802 Mcdowell View\nSan Juan, US'), FALSE, 'N/A', 'N/A', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 0, 100.31, 0, FALSE, 'Change agent everyone front fall. Them total west. Character yeah wear political yard. I mention property relationship.', 'N/A', 34697077554, '72468200', FALSE) [22007-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:140)
	at org.h2.value.Value.convertToTimestamp(Value.java:1099)
	at org.h2.value.Value.convertTo(Value.java:778)
	at org.h2.value.Value.convertTo(Value.java:735)
	at org.h2.table.Column.convert(Column.java:199)
	at org.h2.command.dml.Insert.insertRows(Insert.java:164)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: N/A
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:366)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:528)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:138)
	... 13 more
2021-10-09 17:58:17 jdbc[68]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "TIMESTAMP" constant "N/A"; SQL statement:
INSERT INTO "order_entity" ("id", "active", "address", "delivery", "driver_note", "delivery_slot", "driver_accept", "order_complete", "placed", "restaurant_accept", "restaurant_complete", "restaurant_start", "delivery_price", "food_price", "tip", "refunded", "restaurant_note", "driver_user_id", "user_id", "confirmation_code", "payment_confirmed") VALUES (66362010318, false, E'44751 Cordova Mount
Woodlawn, US', false, E'N/A', E'N/A', false, false, true, false, false, false, 0, 35.45, 0, true, E'Test try matter outside training break myself.', E'N/A', 23827473855, E'69993429', true) -- (66362010318, FALSE, STRINGDECODE('44751 Cordova Mount\nWoodlawn, US'), FALSE, 'N/A', 'N/A', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 0, 35.45, 0, TRUE, 'Test try matter outside training break myself.', 'N/A', 23827473855, '69993429', TRUE) [22007-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:140)
	at org.h2.value.Value.convertToTimestamp(Value.java:1099)
	at org.h2.value.Value.convertTo(Value.java:778)
	at org.h2.value.Value.convertTo(Value.java:735)
	at org.h2.table.Column.convert(Column.java:199)
	at org.h2.command.dml.Insert.insertRows(Insert.java:164)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: N/A
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:366)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:528)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:138)
	... 13 more
2021-10-09 17:58:44 jdbc[71]: exception
org.h2.jdbc.JdbcSQLDataException: Cannot parse "TIMESTAMP" constant "N/A"; SQL statement:
INSERT INTO "order_entity" ("id", "active", "address", "delivery", "driver_note", "delivery_slot", "driver_accept", "order_complete", "placed", "restaurant_accept", "restaurant_complete", "restaurant_start", "delivery_price", "food_price", "tip", "refunded", "restaurant_note", "driver_user_id", "user_id", "confirmation_code", "payment_confirmed") VALUES (90955675202, true, E'55926 Lawrence Plain Suite 237
Schererville, US', false, E'N/A', E'N/A', false, false, true, false, false, false, 0, 74.27, 0, false, E'Information you any rule shoulder. Knowledge inside red side.', E'N/A', 84498282969, E'25595803', true) -- (90955675202, TRUE, STRINGDECODE('55926 Lawrence Plain Suite 237\nSchererville, US'), FALSE, 'N/A', 'N/A', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 0, 74.27, 0, FALSE, 'Information you any rule shoulder. Knowledge inside red side.', 'N/A', 84498282969, '25595803', TRUE) [22007-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:140)
	at org.h2.value.Value.convertToTimestamp(Value.java:1099)
	at org.h2.value.Value.convertTo(Value.java:778)
	at org.h2.value.Value.convertTo(Value.java:735)
	at org.h2.table.Column.convert(Column.java:199)
	at org.h2.command.dml.Insert.insertRows(Insert.java:164)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: N/A
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:366)
	at org.h2.util.DateTimeUtils.parseTimestamp(DateTimeUtils.java:528)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:138)
	... 13 more
2021-10-09 20:05:36 jdbc[109]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "id" not found; SQL statement:
 INSERT INTO "order_entity_items" ("id", "restaurant_id") VALUES (1066622103, 10884743972)  [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:708)
	at org.h2.command.Parser.parseColumn(Parser.java:1377)
	at org.h2.command.Parser.parseColumnList(Parser.java:1362)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1731)
	at org.h2.command.Parser.parseInsert(Parser.java:1684)
	at org.h2.command.Parser.parsePrepared(Parser.java:891)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-09 21:01:03 jdbc[123]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:242)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:182)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:299)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:782)
	at org.h2.server.web.WebApp.login(WebApp.java:1004)
	at org.h2.server.web.WebApp.process(WebApp.java:219)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 15 more
2021-10-09 21:09:41 jdbc[136]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "orders_id" not found; SQL statement:
 INSERT INTO "user_entity_order_list" ("user_entity_id", "orders_id") VALUES (8944796345, 37553201589)  [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:708)
	at org.h2.command.Parser.parseColumn(Parser.java:1377)
	at org.h2.command.Parser.parseColumnList(Parser.java:1362)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1731)
	at org.h2.command.Parser.parseInsert(Parser.java:1684)
	at org.h2.command.Parser.parsePrepared(Parser.java:891)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-09 22:24:21 jdbc[150]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "order_entity_id" not found; SQL statement:
 INSERT INTO "food_order_entity_order_items" ("order_entity_id", "items_id") VALUES (49361933112, 33926330171)  [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:708)
	at org.h2.command.Parser.parseColumn(Parser.java:1377)
	at org.h2.command.Parser.parseColumnList(Parser.java:1362)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1731)
	at org.h2.command.Parser.parseInsert(Parser.java:1684)
	at org.h2.command.Parser.parsePrepared(Parser.java:891)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-09 22:24:27 jdbc[158]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "order_entity_id" not found; SQL statement:
 INSERT INTO "food_order_entity_order_items" ("order_entity_id", "items_id") VALUES (60057869114, 23880531818)  [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:708)
	at org.h2.command.Parser.parseColumn(Parser.java:1377)
	at org.h2.command.Parser.parseColumnList(Parser.java:1362)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1731)
	at org.h2.command.Parser.parseInsert(Parser.java:1684)
	at org.h2.command.Parser.parsePrepared(Parser.java:891)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-09 22:51:33 jdbc[167]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "order_entity_id" not found; SQL statement:
 INSERT INTO "food_order_entity_order_items" ("order_entity_id", "items_id") VALUES (59423267000, 49361933112)  [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:708)
	at org.h2.command.Parser.parseColumn(Parser.java:1377)
	at org.h2.command.Parser.parseColumnList(Parser.java:1362)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1731)
	at org.h2.command.Parser.parseInsert(Parser.java:1684)
	at org.h2.command.Parser.parsePrepared(Parser.java:891)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-17 15:54:03 jdbc[305]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "active" not found; SQL statement:
 INSERT INTO "food_order_entity" ("id", "active", "address", "delivery", "driver_note", "delivery_slot", "driver_accept", "driver_complete", "order_complete", "placed", "restaurant_accept", "restaurant_complete", "restaurant_start", "delivery_price", "food_price", "tip", "refunded", "restaurant_note", "driver_user_id", "user_id", "confirmation_code", "payment_confirmed") VALUES (81911325759, true, E'691 Jones Forks Apt. 546
Kearns, US', NULL, NULL, NULL, NULL, NULL, NULL, '2021-09-28T01:12:56'::timestamp, NULL, NULL, NULL, NULL, 50.67, NULL, false, E'Bag sort live since. Just be blood education model.', NULL, 3381038034, NULL, false)  [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:708)
	at org.h2.command.Parser.parseColumn(Parser.java:1377)
	at org.h2.command.Parser.parseColumnList(Parser.java:1362)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1731)
	at org.h2.command.Parser.parseInsert(Parser.java:1684)
	at org.h2.command.Parser.parsePrepared(Parser.java:891)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-17 15:54:17 jdbc[315]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "active" not found; SQL statement:
 INSERT INTO "food_order_entity" ("id", "active", "address", "delivery", "driver_note", "delivery_slot", "driver_accept", "driver_complete", "order_complete", "placed", "restaurant_accept", "restaurant_complete", "restaurant_start", "delivery_price", "food_price", "tip", "refunded", "restaurant_note", "driver_user_id", "user_id", "confirmation_code", "payment_confirmed") VALUES (11265204812, true, E'95223 Jessica Greens Apt. 540
Redding, US', false, NULL, NULL, NULL, NULL, NULL, '2021-10-12T22:58:30'::timestamp, '2021-10-12T23:07:14'::timestamp, '2021-10-12T23:51:27'::timestamp, '2021-10-12T23:42:38'::timestamp, NULL, 78.01, NULL, false, E'Tell alone summer necessary site black. Nation draw make. Doctor where important go.', NULL, 20369678618, E'70004914', true)  [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:708)
	at org.h2.command.Parser.parseColumn(Parser.java:1377)
	at org.h2.command.Parser.parseColumnList(Parser.java:1362)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1731)
	at org.h2.command.Parser.parseInsert(Parser.java:1684)
	at org.h2.command.Parser.parsePrepared(Parser.java:891)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-17 18:10:51 jdbc[325]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "active" not found; SQL statement:
 INSERT INTO "food_order_entity" ("id", "active", "address", "delivery", "driver_note", "delivery_slot", "driver_accept", "driver_complete", "order_complete", "placed", "restaurant_accept", "restaurant_complete", "restaurant_start", "delivery_price", "food_price", "tip", "refunded", "restaurant_note", "driver_user_id", "user_id", "confirmation_code", "payment_confirmed") VALUES (46542757390, false, E'5807 Taylor Estate Suite 794
Far Rockaway, US', true, E'Position effort drive idea. Husband as thought somebody throughout hair. Government involve mean eye seem outside they western.', '2021-10-02T15:15:41'::timestamp, '2021-10-02T14:35:02'::timestamp, '2021-10-02T14:53:43'::timestamp, '2021-10-02T15:00:48'::timestamp, '2021-10-02T13:58:00'::timestamp, '2021-10-02T14:13:19'::timestamp, '2021-10-02T14:47:16'::timestamp, '2021-10-02T14:20:29'::timestamp, 5.76, 88.75, 32.31, true, E'Anything develop want save compare sure. Up above want add keep black agent. Red small account drop wife audience.', 59645153991, 13817972682, E'87599314', true)  [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.table.Table.getColumn(Table.java:708)
	at org.h2.command.Parser.parseColumn(Parser.java:1377)
	at org.h2.command.Parser.parseColumnList(Parser.java:1362)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1731)
	at org.h2.command.Parser.parseInsert(Parser.java:1684)
	at org.h2.command.Parser.parsePrepared(Parser.java:891)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:422)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-17 20:06:35 jdbc[1821]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:242)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:182)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:228)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:99)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 8 more
2021-10-25 18:10:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
SELECT * FROM "user_entity" where id = 2686844770 [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:205)
	at org.h2.command.dml.Select.prepare(Select.java:1248)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-25 18:10:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ID" not found; SQL statement:
SELECT * FROM "user_entity" where id = "2686844770" [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:205)
	at org.h2.command.dml.Select.prepare(Select.java:1248)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:833)
2021-10-25 18:10:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "2686844770" not found; SQL statement:
SELECT * FROM "user_entity" where "id" = "2686844770" [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:207)
	at org.h2.command.dml.Select.prepare(Select.java:1248)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:833)
